### ISSUE TITLE
Vulnerabilità per lettura carta di produzione in ambiente di collaudo

### ISSUE THREAD

**Issue by valentinacala** [italia/cieid-android-sdk#7]
Facendo alcuni test in ambiente di COLLAUDO ho notato un comportamento anomalo  scannerizzando una carta di PRODUZIONE. In particolare risulta possibile tentare l'autenticazione provando un numero indefinito di pin fino, potenzialmente, ad individuare il pin corretto.

Si presentano infatti due scenari diversi:
- se il pin è **errato**: viene emanato l'evento "ON_PIN_ERROR" con un conteggio progressivo, ma non vincolante, dei tentativi rimanenti (riprovando con una nuova sessione il conteggio si azzera)
- se il pin è **corretto**: viene emanato il seguente errore: 
```
Read error: ssl=0x900feb80: Failure in SSL library, usually a protocol error
error:100c5416:SSL routines:ssl3_read_bytes:SSLV3_ALERT_CERTIFICATE_UNKNOWN (external/boringssl/src/ssl/s3_pkt.c:972 0x8f9d6bc0:0x00000001)
error:100c50e3:SSL routines:ssl3_read_bytes:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/s3_pkt.c:756 0xa92f07f7:0x00000000)
```

**Comment by fventola89** [comment]
Nel caso di pin errato non ci risulta questo comportamento, i possibili tentativi sono 3 e vengono salvati sul sistema operativo della smartcard, non sono azzerabili o aggirabili.

Il caso di pin corretto è il server che indica che il certificato di test(collaudo) non è valido con l'errore indicato.
